
#................................................
# In case I have to use docker credentials see:
#    https://stackoverflow.com/a/64051330/8302386
#................................................


on:
  push:
    branches: main

name: docker_cv

jobs:
  build:
    name: create the curriculum vitae pdf file
    runs-on: ubuntu-latest
    container:
      image: mlampros/mycvitae:rstudiodev
    steps:
     - name: Set up Git repository
       uses: actions/checkout@v2
     - name: install texlive
       run: |
          sudo apt-get -y update
          sudo apt-get install -y texlive-base texlive-latex-base
          sudo apt-get install -y texlive-latex-recommended
          sudo apt-get install -y texlive-xetex
          sudo apt-get install -y texlive-fonts-extra
     - name: render the curriculum vitae
       run: |
         Rscript -e "print(getwd())"
         Rscript -e "rmarkdown::render(input = file.path(getwd(), 'CV', 'CV.Rmd'), params = list(work_dir = getwd()))"
# https://github.com/actions/checkout/pull/1184
     - name: Commit files
       run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -am "add the CV.pdf file to the 'CV' directory of the repository"
          git push
     - name: Upload pdf file
       uses: actions/upload-artifact@v1
       with:
         name: CV
         path: CV/
