
#................................................
# In case I have to use docker credentials see:
#    https://stackoverflow.com/a/64051330/8302386
#................................................

# May be modified with cron job to regularly update but I did not see a purpose
# for my non-dynamic rmd file
on:
  push:
    branches: main

name: docker_cv

jobs:
  build:
    name: create the curriculum vitae pdf file
    runs-on: ubuntu-latest
# Need to docker pull and tag to create your own docker image
    container:
      image: mlampros/mycvitae:rstudiodev
    steps:
     - name: Set up Git repository
       uses: actions/checkout@v2
     - name: install texlive
       run: |
          sudo apt-get -y update
          sudo apt-get install -y texlive-base texlive-latex-base
          sudo apt-get install -y texlive-latex-recommended
          sudo apt-get install -y texlive-xetex
          sudo apt-get install -y texlive-fonts-extra
     - name: render the curriculum vitae
       run: |
         Rscript -e "print(getwd())"
         Rscript -e "rmarkdown::render(input = file.path(getwd(), 'CV', 'CV.Rmd'), params = list(work_dir = getwd()))"
# If this commit fails, try -> https://github.com/actions/checkout/pull/1184
     - name: Commit files
       run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add the CV.pdf file to the 'CV' directory of the repository"
          git push
     - name: Upload pdf file
       uses: actions/upload-artifact@v1
       with:
         name: CV
         path: CV/
     - name: Install jq
       run: |
         sudo apt-get update
         sudo apt-get install -y jq
     - name: Create Tag and Release
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_FILE_NAME: CV.pdf
       run: |
          bash ./entrypoint.sh

